# Generated by Django 3.2.9 on 2022-06-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Admin',
            new_name='isAdmin',
        ),
    ]
