# Generated by Django 3.2.9 on 2022-06-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_is_admin_user_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
